<a href="https://colab.research.google.com/github/grjadhav409/Cheminformatics-/blob/master/Molecular_Featurization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Dataset

In [1]:
import pandas as pd

In [2]:
# read csv file from URL and take only top 5 molecules for simplicity

df_mols = pd.read_csv("https://raw.githubusercontent.com/grjadhav409/Cheminformatics-/master/data/chembl_herg_log_activity.csv").head(5)

In [3]:
df_mols

                                              smiles  pIC50
0     Brc1cc(CCN2CCN(CCc3ccc4C(=O)OCc4c3)CC2)ccc1C#N   6.25
1   Brc1ccc(CNC(=O)C2N(CCc3ccccn3)C(=O)c4ccccc24)cc1   5.03
2  Brc1ccc(NC(=O)N2CCN(C[C@@H]3CCCN(C3)C4CC4)CC2)cc1   5.15
3    Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)NCc4ccccc4   6.75
4     Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)Nc4ccccc4   6.73

# Mordred Descriptors

In [4]:
!pip install 'mordred[full]'  # install with extra requires

!pip install rdkit-pypi

import pandas as pd

from multiprocessing import freeze_support

from rdkit import Chem

from mordred import Calculator, descriptors

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mordred[full] in /usr/local/lib/python3.7/dist-packages (1.2.0)
Requirement already satisfied: numpy==1.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.21.6)
Requirement already satisfied: six==1.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.15.0)
Requirement already satisfied: networkx==2.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (2.6.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.3.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (4.64.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mordred[full]) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mordred[full]) (2.8.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.7/dist-packages (2022.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (1.21.6)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (7.1.2)

In [5]:
name = df_mols['smiles'].tolist()
molecules =[]
for i in name:
  molecules.append(Chem.MolFromSmiles(i))
if __name__ == "__main__":
    freeze_support()
    # Create Calculator
    calc = Calculator(descriptors)
mordred = pd.DataFrame(data=calc.pandas(molecules))
mordred

100%|██████████| 5/5 [00:03<00:00,  1.56it/s]

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,22.724876,15.984643,0,2,38.320650,2.408684,4.724228,38.320650,1.321402,4.300586,...,10.185843,78.321873,453.105189,8.549155,2877,43,152.0,177.0,8.250000,6.416667
1,22.712946,17.546674,0,0,38.417866,2.521395,4.837913,38.417866,1.324754,4.300967,...,10.243347,79.060211,449.073889,9.164773,2351,45,152.0,179.0,8.250000,6.416667
2,20.643996,14.873804,0,2,34.593030,2.387060,4.716103,34.593030,1.330501,4.218872,...,10.082846,79.283858,420.152474,7.639136,1998,37,138.0,160.0,6.888889,5.638889
3,22.684436,17.453866,0,1,38.716965,2.408496,4.809706,38.716965,1.335068,4.297599,...,10.144275,77.404018,455.157225,7.714529,2375,42,150.0,174.0,7.638889,6.444444
4,21.977329,17.095256,0,1,37.150547,2.413010,4.819454,37.150547,1.326805,4.266106,...,10.138678,76.309931,441.141575,7.877528,2099,41,146.0,170.0,7.388889,6.194444

# padel

In [6]:
! pip install padelpy
from padelpy import from_smiles
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: padelpy in /usr/local/lib/python3.7/dist-packages (0.1.12)

Padel descriptors + pubchem fingerprints

In [7]:
smiles = df_mols['smiles'].tolist()
A= []
for i in smiles:
  c =from_smiles(i, fingerprints=True, descriptors=True)
  A.append(c)
discriptors = pd.DataFrame(data = A)
discriptors

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,0,1.4512000000000018,2.105981440000005,68.77440000000001,64.43703199999996,12,12,53,29,24,...,0,0,0,0,0,0,0,0,0,0
1,0,-0.8027000000000002,0.6443272900000003,39.1409,61.769859999999966,18,18,49,29,20,...,0,0,0,0,0,0,0,0,0,0
2,0,-0.5961999999999994,0.35545443999999926,76.71039999999999,62.78899699999995,6,6,55,26,29,...,0,0,0,0,0,0,0,0,0,0
3,0,-1.519700000000001,2.309488090000003,59.8417,69.39578999999995,12,12,59,29,30,...,0,0,0,0,0,0,0,0,0,0
4,0,-1.5313000000000014,2.3448796900000044,55.12950000000001,66.30220399999996,12,12,56,28,28,...,0,0,0,0,0,0,0,0,0,0

# Lipinski Score

In [8]:
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski

def lipinski(smiles, verbose=False):
    moldata= []
    for elem in smiles:
        mol=Chem.MolFromSmiles(elem) 
        moldata.append(mol)       
    baseData= np.arange(1,1)
    i=0  
    for mol in moldata:               
        desc_MolWt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_NumHDonors = Lipinski.NumHDonors(mol)
        desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)           
        row = np.array([desc_MolWt,
                        desc_MolLogP,
                        desc_NumHDonors,
                        desc_NumHAcceptors])       
        if(i==0):
            baseData=row
        else:
            baseData=np.vstack([baseData, row])
        i=i+1          
    columnNames=["MW","LogP","NumHDonors","NumHAcceptors"]   
    descriptors = pd.DataFrame(data=baseData,columns=columnNames)
    
    return descriptors


df_lipinski = lipinski(df_mols.smiles)
df_lipinski["smiles"] = df_mols.smiles.to_list()
df_lipinski

,MW,LogP,NumHDonors,NumHAcceptors,smiles
0,454.368,3.39398,0.0,5.0,Brc1cc(CCN2CCN(CCc3ccc4C(=O)OCc4c3)CC2)ccc1C#N
1,450.336,3.90010,1.0,3.0,Brc1ccc(CNC(=O)C2N(CCc3ccccn3)C(=O)c4ccccc24)cc1
2,421.383,3.47300,1.0,3.0,Brc1ccc(NC(=O)N2CCN(C[C@@H]3CCCN(C3)C4CC4)CC2)cc1
3,456.428,5.57230,1.0,2.0,Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)NCc4ccccc4
4,442.401,5.89460,1.0,2.0,Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)Nc4ccccc4

# Deepchem
 - Circular Fingerprint
 - MACCS Keys Fingerprint
 - PubChem Fingerprint
 - RDKit Descriptors 
 - Mordred Descriptors

In [9]:
!pip install deepchem
!pip install git+https://github.com/mordred-descriptor/mordred
!pip install rdkit-pypi
!pip install pubchempy
import deepchem as dc
import numpy as np
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: deepchem in /usr/local/lib/python3.7/dist-packages (2.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.7.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.3.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.0.2)
Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.7/dist-packages (from deepchem) (2022.3.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.2.0)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->deepchem) (1.15.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi->deepchem) (7.1.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->deepchem) (3.1.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/mordred-descriptor/mordred
  Cloning https://github.com/mordred-descriptor/mordred to /tmp/pip-req-build-vs114vus
  Running command git clone -q https://github.com/mordred-descriptor/mordred /tmp/pip-req-build-vs114vus
Requirement already satisfied: six==1.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (1.15.0)
Requirement already satisfied: numpy==1.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (1.21.6)
Requirement already satisfied: networkx==2.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (2.6.3)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.7/dist-packages (2022.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (1.21.6)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (7.1.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pubchempy in /usr/local/lib/python3.7/dist-packages (1.0.4)

In [10]:
smile = df_mols['smiles'].tolist()
smile

['Brc1cc(CCN2CCN(CCc3ccc4C(=O)OCc4c3)CC2)ccc1C#N',
 'Brc1ccc(CNC(=O)C2N(CCc3ccccn3)C(=O)c4ccccc24)cc1',
 'Brc1ccc(NC(=O)N2CCN(C[C@@H]3CCCN(C3)C4CC4)CC2)cc1',
 'Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)NCc4ccccc4',
 'Brc1ccc(cc1)N(C2CCN(CC2)C3CCCC3)C(=O)Nc4ccccc4']

In [13]:
featurizer = dc.feat.CircularFingerprint(size=1024)
#featurizer = dc.feat.MACCSKeysFingerprint()
#featurizer = dc.feat.PubChemFingerprint() #required rdkit and pubchempy installed
#featurizer = dc.feat.RDKitDescriptors(use_fragment=True, ipc_avg=True)
#featurizer = dc.feat.MordredDescriptors(ignore_3D = False)



discriptors = featurizer.featurize(smiles)
df = pd.DataFrame(data=discriptors)
df

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0